# Generated by Django 6.0.2 on 2026-02-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stocked_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='stores.aisle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
